[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lyte"
version = "0.1.2"
description = "🧚 Python lighting player for all lights 🧚"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mido",
    "numpy",
    "pydantic",
    "python-rtmidi",
    "reccy",
    "tomlkit",
    "tyro",
    "ufor",
]

[project.scripts]
lyte = "lyte.cli:main"

[tool.setuptools.packages.find]
include = ["lyte", "lyte.*"]

[tool.ruff.format]
quote-style = "single"

[dependency-groups]
dev = [
    "pytest",
    "pytest-xdist",
    "pytest-regressions",
    "pyupgrade",
    "ruff",
    "ty",
]

[tool.pytest.ini_options]
addopts = "-n auto"

[tool.ty.environment]
root = ["."]
extra-paths = ["type_stubs"]

[tool.uv]
exclude-newer = "1 week"

[tool.uv.sources]
reccy = { git = "https://github.com/rec/reccy.git", branch = "main" }
ufor = { git = "https://github.com/rec/ufor.git", branch = "main" }
