"""Small dependency-free Lyte client."""

from .animation import Animation, Device, State, validate_frame
from .bibliopixel import (
    Alternates,
    ColorChase,
    ColorFade,
    ColorFill,
    ColorPattern,
    ColorWipe,
    FireFlies,
    HalvesRainbow,
    LarsonScanner,
    LinearRainbow,
    PartyMode,
    PixelPingPong,
    Pulse,
    Rainbow,
    RainbowCycle,
    SaberBlade,
    Searchlights,
    Twinkle,
    Wave,
    WhiteTwinkle,
)
from .client import LyteClient
from .discovery import DiscoveredDevice, discover
from .errors import (
    AuthenticationError,
    DiscoveryError,
    LyteError,
    ProtocolError,
)
from .hamiltonian import (
    Hamiltonian,
    HamiltonianCounter,
    HamiltonianState,
    hamiltonian_colors,
)
from .preview import Layout, animation_document, render_animation_html
from .random_walk import RandomWalk
from .retry import RetryConfig, retry_call
from .session import (
    authenticate_with_retry,
    led_count_from_gestalt,
    read_gestalt,
    send_frame_with_retry,
    set_mac_from_gestalt,
    set_off_mode_with_retry,
    set_realtime_mode_with_retry,
)

__all__ = [
    "AuthenticationError",
    "Alternates",
    "Animation",
    "ColorChase",
    "ColorFade",
    "ColorFill",
    "ColorPattern",
    "ColorWipe",
    "FireFlies",
    "HalvesRainbow",
    "DiscoveredDevice",
    "DiscoveryError",
    "Device",
    "Hamiltonian",
    "HamiltonianCounter",
    "HamiltonianState",
    "hamiltonian_colors",
    "LarsonScanner",
    "LinearRainbow",
    "Layout",
    "PartyMode",
    "PixelPingPong",
    "ProtocolError",
    "Pulse",
    "Rainbow",
    "RainbowCycle",
    "RandomWalk",
    "SaberBlade",
    "Searchlights",
    "LyteClient",
    "LyteError",
    "RetryConfig",
    "State",
    "Twinkle",
    "Wave",
    "WhiteTwinkle",
    "authenticate_with_retry",
    "animation_document",
    "discover",
    "retry_call",
    "led_count_from_gestalt",
    "read_gestalt",
    "render_animation_html",
    "send_frame_with_retry",
    "set_off_mode_with_retry",
    "set_mac_from_gestalt",
    "set_realtime_mode_with_retry",
    "validate_frame",
]
