"""Small dependency-free Lyte client."""

from .animation import (
    Animation,
    Device,
    State,
    byte_light_frame_from_float,
    float_color_from_rgb,
    rgb_from_float_color,
    solid_float_light_frame,
    validate_byte_rgb_frame,
    validate_float_light_frame,
    validate_frame,
)
from .animations.bibliopixel import (
    Alternates,
    ColorChase,
    ColorFade,
    ColorFill,
    ColorPattern,
    ColorWipe,
    FireFlies,
    HalvesRainbow,
    LarsonScanner,
    LinearRainbow,
    PartyMode,
    PixelPingPong,
    Pulse,
    Rainbow,
    RainbowCycle,
    SaberBlade,
    Searchlights,
    Twinkle,
    Wave,
    WhiteTwinkle,
)
from .animations.hamiltonian import (
    Hamiltonian,
    HamiltonianCounter,
    HamiltonianState,
    hamiltonian_colors,
)
from .animations.random_walk import RandomWalk
from .errors import (
    AuthenticationError,
    DiscoveryError,
    LyteError,
    ProtocolError,
    UnsupportedEndpointError,
)
from .preview import Layout, animation_document, render_animation_html
from .retry import RetryConfig, retry_call
from .twinkly.client import TwinklyClient
from .twinkly.diagnostic import (
    DiagnosticConfig,
    TwinklyDeviceInfo,
    TwinklyEndpointReport,
)
from .twinkly.discovery import DiscoveredDevice, discover
from .twinkly.session import (
    authenticate_with_retry,
    led_count_from_gestalt,
    read_gestalt,
    send_frame_with_retry,
    set_mac_from_gestalt,
    set_off_mode_with_retry,
    set_realtime_mode_with_retry,
    twinkly_request_label,
)

__all__ = [
    'AuthenticationError',
    'Alternates',
    'Animation',
    'byte_light_frame_from_float',
    'ColorChase',
    'ColorFade',
    'ColorFill',
    'ColorPattern',
    'ColorWipe',
    'FireFlies',
    'float_color_from_rgb',
    'HalvesRainbow',
    'DiscoveredDevice',
    'DiscoveryError',
    'Device',
    'DiagnosticConfig',
    'Hamiltonian',
    'HamiltonianCounter',
    'HamiltonianState',
    'hamiltonian_colors',
    'LarsonScanner',
    'LinearRainbow',
    'Layout',
    'PartyMode',
    'PixelPingPong',
    'ProtocolError',
    'Pulse',
    'Rainbow',
    'RainbowCycle',
    'RandomWalk',
    'SaberBlade',
    'Searchlights',
    'TwinklyClient',
    'LyteError',
    'RetryConfig',
    'State',
    'Twinkle',
    'TwinklyDeviceInfo',
    'Wave',
    'WhiteTwinkle',
    'TwinklyEndpointReport',
    'authenticate_with_retry',
    'animation_document',
    'discover',
    'retry_call',
    'led_count_from_gestalt',
    'read_gestalt',
    'render_animation_html',
    'rgb_from_float_color',
    'send_frame_with_retry',
    'set_off_mode_with_retry',
    'set_mac_from_gestalt',
    'set_realtime_mode_with_retry',
    'solid_float_light_frame',
    'UnsupportedEndpointError',
    'validate_byte_rgb_frame',
    'validate_float_light_frame',
    'validate_frame',
    'twinkly_request_label',
]
