library_config = "library.toml"
fps = 30
initial_animation = "tree_show"

[twinkly]
left = { product_name = "Dots" }
right = {}

[animations.tree_show]
selector = "examples:/composition.toml"
outputs = { light = "left + right" }
